### ISSUE TITLE
Add some general introductory text to the README.md file

### ISSUE THREAD

**Issue by DanJonesOcean** [so-wise/so-fronts#2]
We could use some text from the AGU abstract. How about this? 

> In the Southern Ocean, fronts delineate water masses, which correspond to upwelling and downwelling branches of the overturning circulation. Classically, oceanographers define Southern Ocean fronts as a small number of continuous linear features that encircle Antarctica. However, modern observational and theoretical developments are challenging this traditional framework to accommodate more localized views of fronts [Chapman et al. 2020]. 
> 
> Here we present code for implementing two related methods for calculating fronts from oceanographic data. The first method uses unsupervised classification (specifically, Gaussian Mixture Modeling or GMM) and a novel interclass metric to define fronts. This approach produces a discontinuous, probabilistic view of front location, emphasising the fact that the boundaries between water masses are not uniformly sharp across the entire Southern Ocean. 
> 
> The second method uses Sobel edge detection to highlight rapid changes [Hjelmervik & Hjelmervik, 2019]. This approach produces a more local view of fronts, with the advantage that it can highlight the movement of individual eddy-like features (such as the Agulhas rings). 

Then we can make sure that the references are present too, perhaps simply as hyperlinks to the papers.

**Comment by sdat2** [comment]
Hopefully that's done :)
